### ISSUE TITLE
Cropping not resizing

### ISSUE THREAD

**Issue by dikum** [Nimrod007/PHP_image_resize#15] opened 2016-10-06 12:15 UTC
The new image created is being cropped not resized. For example i upload an image of 500x500 and give a new dimension of 300x300. This crops the image which makes it lose some parts of it. Please how can i get the full image to be displayed(something like shrink) but with the new dimensions. Thank you.

**Comment by dikum** [comment] 2016-10-06 14:33
What I mean is I actually want to scale the image and not resize.

**Comment by Rirajojo** [comment] 2016-10-07 20:40
If you only want to scale the usual way should comply.

<img src="images/uploads/picture.jpg"  width="300" height="300">

**Comment by dikum** [comment] 2016-10-11 09:56
Simple and straight forward. Didn't think of that. I used imagescale() before now. Thanks.

**Comment by flaver12** [comment] 2016-10-12 22:11
Its not a good style to do it, better is it to actually scale the image down

**Comment by Khalilbz** [comment] 2016-10-13 11:21
Seriously, The issue is marked as opened with an HTML solution, that solution for Mr.Dikum not for the issue I have the same problem and I want it to work with PHP, So please help

**Comment by flaver12** [comment] 2016-10-14 08:35
Well scaling a img down us not that hard,
you maybe say you have a scaling of 40% so than its simple mat e.g
Width origin: 100px than you just remove 60px because 40% of 100 are 40 .

Hope it helps

**Comment by Nimrod007** [comment] 2016-10-26 17:52
since a new issue is opened for this, closing this 1 
thanks

**Closed by Nimrod007** 2016-10-26 17:52 UTC
